# Generated by Django 4.2 on 2024-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_type', models.CharField(choices=[('proveedor', 'Proveedor'), ('trabajador', 'Trabajador')], max_length=20)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
