# Generated by Django 4.2 on 2024-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='parts_replaced',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
