# Generated by Django 4.2 on 2024-06-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
